# Dependencies
markdown:    rdiscount
highlighter: rouge

# Permalinks
permalink:   pretty

# Server
destination: _gh_pages
host:        127.0.0.1
port:        3000
baseurl:     /GRNmap
encoding:    UTF-8
