runtests({
    
          'populateGlobalsTest', ...
          'matrixDimensionsTest', ...
          'deletedStrainTest', ...
          'LSETest' ...
          'initializeArraysTest', ...
          'optimizationDiagnosticTest', ...
          'localizedVariablesReadInputSheetTest', ...
        });