runtests({
          'globalsToLocalTest',...
          'populateGlobalsTest', ...
          'matrixDimensionsTest', ...
          'deletedStrainTest', ...
          'LSETest' ...
          'initializeArraysTest', ...
          'optimizationDiagnosticTest', ...
          'localizedVariablesReadInputSheetTest', ...
          'compressMissingDataTest', ...
          'convertToNestedStructureTest', ...
        });