runtests({'deletedStrainTest', ...
          'LSETest', ...
          'initializeArraysTest', ...
%           'MSETest', ...
          'optimizationDiagnosticTest', ...
          'populateGlobalsTest'});