classdef ConstantGRNstructs 
   properties (Constant)
         MM_estimation_fixP0_graph = struct( ...
             'globals', struct( ...
                 'Strain',{},...
                 'expression_timepoints', [],...
                 'prorate', [], ...
                 'degrate', [], ...
                 'is_forced', [],...
                 'adjacency_mat', [],...
                 'wts', [],...
                 'b', [],...
                 'alpha', 0,...
                 'num_genes', 0,...
                 'num_times', 0,...
                 'fix_b', 0,...
                 'no_inputs', [], ...
                 'production_function', 'String',...
                 'log2FC', struct(...
                     'model', {;;},...
                     'data', {;;}...
                 )...
              ), ...
             'labels', struct(...
                  'TX0', {},...
                  'TX2', {} ...
             ),...
             'microData', struct(...
                 'model', {;;},...
                 'data', {;;},...
                 'stdev', {;;}...
             ),...
             'controlParams', struct(...
                 'simulation_timepoints', [],...
                 'estimate_params', 0,...
                 'L_curve', 0,...
                 'make_graphs', 0,...
                 'fix_b', 0,...
                 'production_function', 'String'...
             ),...
             'GRNOutput', struct(...
                 'SSE', [],...
                 'lse_out',[],...
                 'reg_out',[],...
                 'counter',1 ...
             ),...
             'GRNParams', struct(...
                 'num_genes', 0, ...
                 'num_forced', 0, ...
                 'no_inputs', [], ...
                 'positions', [], ...
                 'minLSE', [], ...
                 'active', [] ...
             ),...
             'locals', struct(...
                 'estimated_guesses', [], ...
                 'initial_guesses', [], ...
             )...
             'directory', 'String',...
             'inputFile', 'String',...
             'copy_counter', 0,...
             'alpha_list_length', 0 ...
         );
         MM_estimation_fixP0_nograph = struct()
         MM_estimation_fixP1_graph 
         MM_estimation_fixP1_nograph 
         MM_forward_graph 
         MM_forward_nograph 
         Sigmoidal_estimation_fixb0_fixP0_graph 
         Sigmoidal_estimation_fixb0_fixP0_nograph 
         Sigmoidal_estimation_fixb0_fixP1_graph 
         Sigmoidal_estimation_fixb0_fixP1_nograph 
         Sigmoidal_estimation_fixb1_fixP0_graph 
         Sigmoidal_estimation_fixb1_fixP0_nograph 
         Sigmoidal_estimation_fixb1_fixP1_graph 
         Sigmoidal_estimation_fixb1_fixP1_nograph 
         Sigmoidal_forward_graph 
         Sigmoidal_forward_nograph
         
   end
   
   
    
end